operator:
  enabled: true
  fullnameOverride: "operator"
  nameOverride: "operator"
  image:
    repository: "ghcr.io/formancehq/operator"
    tag: "v2.0.0-rc.26"
  operator:
    disableWebhooks: false
    region: "private"
    env: "private"
    metricsAddr: ":8080"
    probeAddr: ":8081"
    enableLeaderElection: true
agent:
  enabled: false
  image:
    tag: "v2.0.0-rc.26"
  server:
    address: "app.formance.cloud:443"
    tls:
      enabled: true
      insecureSkipVerify: true
  agent:
    id: "aws-eu-west-1-sandbox"
    baseUrl: https://sandbox.formance.cloud
    authentication:
      mode: bearer
      issuer: https://app.formance.cloud/api
      clientID: "REGION_ID"
      clientSecret: ""
versions:
  create: true
  files:
    default:
      orchestration: v0.2.1
      reconciliation: v0.1.0
      search: v0.10.0
      auth: v0.4.4
      wallets: v0.4.6
      webhooks: v2.0.0-rc.26
      payments: v1.0.0-rc.5
      stargate: v0.1.10
      gateway: v2.0.0-rc.26
      ledger: v1.10.14
      operator-utils: v2.0.0-rc.26
    v1.0:
      orchestration: v0.2.1
      reconciliation: v0.1.0
      search: v0.10.0
      auth: v0.4.4
      wallets: v0.4.6
      webhooks: v2.0.0-rc.26
      payments: v1.0.0-rc.5
      stargate: v0.1.10
      gateway: v2.0.0-rc.26
      ledger: v1.10.14
      operator-utils: v2.0.0-rc.26
    v2.0:
      ledger: v2.0.0-rc.26
      search: v2.0.0-rc.26
      stargate: v2.0.0-rc.26
      auth: v2.0.0-rc.26
      wallets: v2.0.0-rc.26
      webhooks: v2.0.0-rc.26
      gateway: v2.0.0-rc.26
      payments: v2.0.0-rc.26
      orchestration: v2.0.0-rc.26
      reconciliation: v2.0.0-rc.26
      operator-utils: v2.0.0-rc.26
