{{ if and .Values.versions.create (.Capabilities.APIVersions.Has "formance.com/v1beta1/Versions") }}
apiVersion: formance.com/v1beta1
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-rc.18
  search: v2.0.0-rc.18
  stargate: v2.0.0-rc.18
  auth: v2.0.0-rc.18
  wallets: v2.0.0-rc.18
  webhooks: v2.0.0-rc.18
  gateway: v2.0.0-rc.18
  payments: v2.0.0-rc.18
  orchestration: v2.0.0-rc.18
  reconciliation: v2.0.0-rc.18
  operator-utils: v2.0.0-rc.18
{{ end }}
