{{ if and .Values.versions.create (.Capabilities.APIVersions.Has "stack.formance.com/v1beta3/Versions") }}
apiVersion: stack.formance.com/v1beta3
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-rc.12
  search: v2.0.0-rc.12
  stargate: v2.0.0-rc.12
  auth: v2.0.0-rc.12
  wallets: v2.0.0-rc.12
  webhooks: v2.0.0-rc.12
  gateway: v2.0.0-rc.12
  payments: v2.0.0-rc.12
  orchestration: v2.0.0-rc.12
  reconciliation: v2.0.0-rc.12
{{ end }}
