{{ if .Capabilities.APIVersions.Has "stack.formance.com/v1beta3/Versions" }}
apiVersion: stack.formance.com/v1beta3
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-beta.16
  search: v2.0.0-beta.16
  stargate: v2.0.0-beta.16
  auth: v0.4.4 #v2.0.0-beta.16
  wallets: v2.0.0-beta.16
  webhooks: v2.0.0-beta.16
  gateway: v2.0.0-beta.16
  payments: v2.0.0-beta.16
  orchestration: v2.0.0-beta.16
  reconciliation: v2.0.0-beta.16
{{ end }}
