{{ if and .Values.versions.create (.Capabilities.APIVersions.Has "formance.com/v1beta1/Versions") }}
apiVersion: formance.com/v1beta1
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-rc.17
  search: v2.0.0-rc.17
  stargate: v2.0.0-rc.17
  auth: v2.0.0-rc.17
  wallets: v2.0.0-rc.17
  webhooks: v2.0.0-rc.17
  gateway: v2.0.0-rc.17
  payments: v2.0.0-rc.17
  orchestration: v2.0.0-rc.17
  reconciliation: v2.0.0-rc.17
  operator-utils: v2.0.0-rc.17
{{ end }}
