{{ if .Capabilities.APIVersions.Has "stack.formance.com/v1beta3/Versions" }}
apiVersion: stack.formance.com/v1beta3
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-beta.8
  search: v2.0.0-beta.8
  stargate: v2.0.0-beta.8
  auth: v2.0.0-beta.8
  wallets: v2.0.0-beta.8
  webhooks: v2.0.0-beta.8
  gateway: v2.0.0-beta.8
  payments: v2.0.0-beta.8
  orchestration: v2.0.0-beta.8
  reconciliation: v2.0.0-beta.8
{{ end }}
