{{ if and .Values.versions.create (.Capabilities.APIVersions.Has "stack.formance.com/v1beta3/Versions") }}
apiVersion: stack.formance.com/v1beta3
kind: Versions
metadata:
  name: v2.0
spec:
  ledger: v2.0.0-rc.6
  search: v2.0.0-rc.6
  stargate: v2.0.0-rc.6
  auth: v2.0.0-rc.6
  wallets: v2.0.0-rc.6
  webhooks: v2.0.0-rc.6
  gateway: v2.0.0-rc.6
  payments: v2.0.0-rc.6
  orchestration: v2.0.0-rc.6
  reconciliation: v2.0.0-rc.6
{{ end }}
