version: "3"

tasks:
  release:
    cmds:
      - task: build
      - for i in $(ls *.tgz); do helm push $i oci://ghcr.io/formancehq/helm; done

  build:
    cmds:
      - task: build:regions
      - task: build:demo

  build:regions:
    dir: ./regions
    cmds:
      - helm dependencies update
      - helm dependencies build
      - helm package ./
      - mv *.tgz ./../

  build:demo:
    dir: ./demo
    cmds:
      - helm dependencies update
      - helm dependencies build
      - helm package ./
      - mv *.tgz ./../
