name: Stack - Release
on:
  push:
    tags:
      - 'releases/v*.*.*'
permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed 's/\.[^.]*$//' >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./releases/versions/${{ env.RELEASE_VERSION }}/main.yaml
            ./releases/versions/${{ env.RELEASE_VERSION }}/openapi.json